### ISSUE TITLE
Find a way to avoid `@dev || xx` constraint for local packages

### ISSUE THREAD

**Issue by soyuka** [soyuka/pmu#4]
Tried:

```
        $requires = [];
        $package = $composer->getPackage();
        foreach ($package->getRequires() as $key => $require) {
            if (in_array($require->getTarget(), $packages, true)) {
                $constraint = $require->getConstraint();
                $prettyString = '*@dev || ' . $constraint->getPrettyString();
                $newConstraint = new MultiConstraint([new MatchAllConstraint(), $constraint], false);
                $newConstraint->setPrettyString($prettyString);
                $require = new Link($require->getSource(), $require->getTarget(), $newConstraint, Link::TYPE_REQUIRE, $prettyString);
            }

            $requires[$key] = $require;
        }

        $package->setRequires($requires);
```

But it doesn't work, it says 
![20240229_18h24m48s_grim](https://github.com/soyuka/pmu/assets/1321971/b152c894-d635-438a-91a6-617c2a542ec4)

**Comment by CrochetFeve0251** [comment]
Hey @soyuka,
I am not sure it is exactly the same issue as here, but it is similar:
![image](https://github.com/user-attachments/assets/d5a86f9a-1a9f-4152-9083-74ecc25bef75)

Let me provide you some context about this screenshot.

This is from Launchpad, a WordPress framework I am working on and which is extremely modular, and due to that it became really hard to keep it stable, and this is why I decided to move to a mono repository.

Inside the repo I have tons of dependencies but lets focus only on the ones important here.

What I succeeded to isolate to recreate the bug is to install the following packages in my mono repo:
- https://github.com/wp-launchpad/bud-assets
- https://github.com/wp-launchpad/front
- https://github.com/wp-launchpad/front-take-off

Then, when you run the command `composer all install` or `composer all update`, it should raise the error mentioned when the libraries are normally working together without any issues.

I created a repo to reproduce the issue with less dependencies: https://github.com/CrochetFeve0251/mono-repo-problem

**Comment by soyuka** [comment]
Use `link` with this plugin instead :)

**Comment by CrochetFeve0251** [comment]
@soyuka Thanks I think I finally got it.

I was trying to reproduce what you had done in your test example.
I didn't get that what you added on the root composer.json wasn't dependencies used by other libraries inside the monorepo but instead the top level library themselves, so then they could have the `"minimum-stability": "dev",` being shared to them and the all-automation work.

Errata I forgot some `"minimum-stability": "dev",` inside of my main library which made it work, but now I removed it, it still doesn't work even if I tried to use the command link on the repo as the `minimum-stability` attribute still refuses dev dependencies :')

**Comment by CrochetFeve0251** [comment]
@soyuka I found why it was failing in my project and implemented a solution (which is not the cleanest for the moment).

The idea is that if you have the following depedencies tree:
A -> B
B -> C

Then PMU will add B as `@dev` inside the `lock` file but for C dependency it will keep it as it is, making the creation from the `lock` file failing.

To fix this issue, I went not only to look at direct dependencies of the first package A but also all packages which are used inside the lock file and could come from the monorepo.
If they were part of the monorepo, added the `@dev` on them, and it looks like it made the trick, and now it works fine.

FYI, the PR is here: https://github.com/soyuka/pmu/pull/15

Feel free to review it, so we can find a more generic solution to access some of the necessary paths.

Also, I didn't add tests to it as for the moment when I try to run them, all are failing. :')
